"use strict";
const CAT={attack:{name:"攻擊",color:"#e58a35"},defense:{name:"防禦",color:"#54aa72"},support:{name:"輔助",color:"#d8bd45"},weaken:{name:"弱化",color:"#c94f55"},amp:{name:"增幅",color:"#4d9dd6"}};
const bonus=n=>n<=1?1:1+Math.min(n,7)*.2-.2;
const img=n=>`assets/icons/螢幕擷取畫面 2026-09-18 ${n}.webp?v=20260918-7`;
const parts=[
 ["atk","高輸出動力增幅器","attack","攻擊力",7,74.5,12.8,"091314"],["as","超頻時脈加速器","attack","攻擊速度",7,49.8,8.5,"091319"],["crit","精密軌跡預測器","attack","暴擊率",7,2.32,5,"091324"],["cdmg","高輸出衝擊增幅器","attack","暴擊傷害",7,58.1,10.1,"091328"],["dmg","超高密度電力聚集器","attack","傷害",7,37.1,5,"091332"],["skill","高效能功能增幅器","attack","技能傷害",7,30.6,5,"091336"],["boss","深層巨體解析器","attack","首領傷害",7,61.8,5,"091340"],
 ["def","絕對防護控制器","defense","防禦力",7,20,4,"091344"],["hp","永久生命維持器","defense","最大生命",7,20,4,"091348"],["reduce","高效率傷害分散器","defense","受到傷害減少",7,6,1,"091352"],["shield","高輸出護盾產生器","defense","護盾",7,12,2,"091356"],["dodge","超前迴避預測器","defense","迴避率",7,4,1,"091400"],["reflect","逆相反擊轉換器","defense","反射傷害",7,8,2,"091404"],["heal","超高速自我修復器","defense","恢復效果",7,10,2,"091408"],
 ["cool","精密時空調節器","support","冷卻時間",7,30.5,4,"091412"],["gold","大容量金幣收集器","support","金幣獲得",7,15,4,"091416"],["exp","超高密度記憶收集器","support","經驗獲得",7,15,4,"091422"],["cc","強制命令阻斷器","support","控制免疫",7,4,1,"091425"],["buff","永續效果維持器","support","增益持續時間",7,2.9,12.9,"091429"],["recover","超高速狀態恢復器","support","異常狀態時間減少",7,14.9,1.5,"091434"],["move","量子機動加速器","support","移動速度",7,24.4,3,"091438"],
 ["weakcrit","高輸出全域弱點增幅器","weaken","敵方暴傷承受",7,5,2,"091444"],["atkdown","強制輸出抑制器","weaken","敵方攻擊降低",7,3,1,"091447"],["defdown","絕對防禦粉碎器","weaken","敵方防禦降低",7,5,2,"091451"],["taken","精準目標弱點增幅器","weaken","敵方受到傷害",7,8,2,"091456"],["asdown","強制攻擊速度限制器","weaken","敵方攻速降低",7,9,2,"091500"],["slow","強制移動限制器","weaken","敵方移速降低",7,9,2,"091504"],["antiheal","高輸出恢復抑制器","weaken","敵方恢復降低",7,8,2,"091508"]
].map(([id,name,cat,effect,max,base,step,pic])=>({id,name,cat,effect,max,base,step,pic:img(pic),amp:false}));
const MAX_VALUES={atk:45,as:15,crit:15,cdmg:45,dmg:20,skill:15,boss:60,def:85,hp:85,reduce:10,shield:85,dodge:10,reflect:15,heal:85,cool:15,gold:25,exp:25,cc:10,buff:15,recover:15,move:10,weakcrit:10,atkdown:15,defdown:20,taken:10,asdown:10,slow:15,antiheal:20};
parts.forEach(part=>part.maxValue=MAX_VALUES[part.id]);
const amps=[
 ["cross","廣域電力分配器","cross",1,"091516"],["row","廣域水平電力匯流排","row",2,"091519"],["col","廣域垂直電力匯流排","col",2,"091523"],["up","遠距上端相位增幅器","up",4,"091526"],["down","遠距下端相位增幅器","down",4,"091531"],["left","遠距左側相位增幅器","left",4,"091535"],["right","遠距右側相位增幅器","right",4,"091538"],["all","廣域全方位共振器","all",1,"091542"]
].map(([id,name,shape,stage,pic])=>({id:"amp-"+id,name,cat:"amp",effect:`範圍內 +${stage}階・可重複放置`,max:0,base:0,step:0,pic:img(pic),amp:true,shape,stage}));
const catalog=[...parts,...amps], byId=Object.fromEntries(catalog.map(x=>[x.id,x]));
const initial=["amp-down","crit","amp-right","move","cool","atk","as","amp-left","cc","amp-up","dmg","amp-col","amp-all","buff","weakcrit","skill","boss","recover","gold","defdown","amp-up","cdmg","taken","atkdown","asdown"];
let state={grid:initial.map((id,i)=>({id,level:({crit:3,move:5,cool:5,atk:5,as:7,cc:1,dmg:5,buff:1,weakcrit:1,skill:5,boss:3,recover:1,gold:1,defdown:1,cdmg:3,taken:1,atkdown:1,asdown:1})[id]||0,rarity:7,variant:"blue",locked:false,base:null,step:null})),selected:null,filter:"all"};
try{const s=JSON.parse(localStorage.getItem("loi-mech-editor-v1"));if(s?.grid?.length===25)state={...state,...s}}catch{}
if(state.strictConnected==null)state.strictConnected=true;
if(!state.mobileFilter)state.mobileFilter="all";
const $=s=>document.querySelector(s), pos=i=>[Math.floor(i/5),i%5], idx=(r,c)=>r*5+c, valid=(r,c)=>r>=0&&r<5&&c>=0&&c<5;
function connected(grid,i){const p=byId[grid[i]?.id];if(!p||p.amp)return[];let seen=new Set([i]),q=[i];while(q.length){let x=q.shift(),[r,c]=pos(x);for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){let y=idx(r+dr,c+dc),yp=byId[grid[y]?.id];if(valid(r+dr,c+dc)&&!seen.has(y)&&yp?.cat===p.cat){seen.add(y);q.push(y)}}}return[...seen]}
function targets(grid,i){return EffectEngine.amplifierTargets(grid,i,byId)}
function calculate(grid=state.grid){let incoming=Array.from({length:25},()=>[]);grid.forEach((g,i)=>targets(grid,i).forEach(t=>incoming[t].push({i,stage:byId[g.id].stage,name:byId[g.id].name})));return grid.map((g,i)=>{let p=byId[g?.id];if(!p)return null;if(p.amp)return{p,g,i,amp:true,targets:targets(grid,i)};let group=connected(grid,i),inc=incoming[i].reduce((s,x)=>s+x.stage,0),level=Math.min(g.rarity??p.max,(g.level||0)+inc),mult=bonus(group.length),final=EffectEngine.finalMaximum(p.maxValue,mult);return{p,g,i,group,inc,level,mult,final,sources:incoming[i]}})}
function save(){localStorage.setItem("loi-mech-editor-v1",JSON.stringify(state))}
function icon(p){return `<div class="icon" style="--cat:${CAT[p.cat].color}"><img src="${p.pic}" alt=""></div>`}
function isMobile(){return window.matchMedia("(max-width: 720px), (pointer: coarse)").matches}
function closeMobilePicker(){document.body.classList.remove("picker-open");$("#mobilePicker").setAttribute("aria-hidden","true");$("#pickerBackdrop").hidden=true;state.pickerTarget=null}
function openMobilePicker(i){if(!isMobile()||state.grid[i])return;state.pickerTarget=i;state.selected=i;$("#pickerTarget").textContent=`放入第 ${i+1} 格`;renderMobilePicker();$("#pickerBackdrop").hidden=false;requestAnimationFrame(()=>{document.body.classList.add("picker-open");$("#mobilePicker").setAttribute("aria-hidden","false")})}
function renderMobilePicker(){let root=$("#mobilePalette");if(!root)return;let fs=["all","attack","defense","support","weaken","amp"],used=new Set(state.grid.filter(Boolean).map(x=>x.id));$("#mobileFilters").innerHTML=fs.map(f=>`<button type="button" data-f="${f}" class="${state.mobileFilter===f?'primary':''}">${f==='all'?'全部':CAT[f].name}</button>`).join("");root.innerHTML=catalog.filter(p=>state.mobileFilter==="all"||p.cat===state.mobileFilter).map(p=>{let disabled=used.has(p.id)&&!p.amp;return`<button type="button" class="mobile-part ${disabled?'used':''}" data-id="${p.id}" ${disabled?'disabled':''} style="--cat:${CAT[p.cat].color}">${icon(p)}<span><strong>${p.name}</strong><small>${CAT[p.cat].name}｜${p.effect}</small></span></button>`}).join("");$("#mobileFilters").onclick=e=>{let f=e.target.dataset.f;if(f){state.mobileFilter=f;renderMobilePicker()}};root.onclick=e=>{let button=e.target.closest(".mobile-part");if(!button||button.disabled||state.pickerTarget==null)return;let result=MobileUI.placePart(state.grid,state.pickerTarget,button.dataset.id,byId);if(!result.ok){flash(result.reason==="duplicate"?"普通零件不可重複":"這一格無法放置");return}state.grid=result.grid;state.selected=state.pickerTarget;closeMobilePicker();render()}}
function render(){renderPalette();renderBoard();renderMobilePicker();renderEditor();renderCalc();save()}
function renderPalette(){let fs=["all","attack","defense","support","weaken","amp"];$("#filters").innerHTML=fs.map(f=>`<button data-f="${f}" class="${state.filter===f?'primary':''}">${f==='all'?'全部':CAT[f].name}</button>`).join("");$("#filters").onclick=e=>{if(e.target.dataset.f){state.filter=e.target.dataset.f;renderPalette()}};let used=new Set(state.grid.filter(Boolean).map(x=>x.id));$("#palette").innerHTML=catalog.filter(p=>state.filter==="all"||p.cat===state.filter).map(p=>`<div class="part-card ${used.has(p.id)&&!p.amp?'used':''}" draggable="true" data-id="${p.id}" style="--cat:${CAT[p.cat].color}">${icon(p)}<div><strong>${p.name}</strong><small>${CAT[p.cat].name}｜${p.effect}</small></div></div>`).join("");document.querySelectorAll(".part-card").forEach(x=>x.ondragstart=e=>e.dataTransfer.setData("text/plain","new:"+x.dataset.id))}
let suppressCellClickUntil=0;
function bindTouchDrag(el,i){if(!state.grid[i])return;let timer=null,active=false,startX=0,startY=0,target=i;const clear=()=>{clearTimeout(timer);timer=null;document.body.classList.remove("touch-dragging");document.querySelectorAll(".touch-drag-source,.touch-drag-target").forEach(x=>x.classList.remove("touch-drag-source","touch-drag-target"))};el.onpointerdown=e=>{if(!isMobile()||e.pointerType==="mouse"||e.target.closest(".lock"))return;startX=e.clientX;startY=e.clientY;target=i;timer=setTimeout(()=>{active=true;el.setPointerCapture(e.pointerId);el.classList.add("touch-drag-source");document.body.classList.add("touch-dragging");navigator.vibrate?.(25)},350)};el.onpointermove=e=>{if(!timer&&!active)return;if(!active&&Math.hypot(e.clientX-startX,e.clientY-startY)>10){clear();return}if(!active)return;e.preventDefault();let hit=document.elementFromPoint(e.clientX,e.clientY)?.closest(".cell");document.querySelectorAll(".touch-drag-target").forEach(x=>x.classList.remove("touch-drag-target"));if(hit){target=+hit.dataset.i;hit.classList.add("touch-drag-target")}};el.onpointerup=e=>{if(!active){clearTimeout(timer);timer=null;return}e.preventDefault();suppressCellClickUntil=Date.now()+400;let result=MobileUI.movePart(state.grid,i,target);clear();if(!result.ok){flash(result.reason==="locked"?"鎖定格無法移動":"無法移動到該位置");return}state.grid=result.grid;state.selected=target;render()};el.onpointercancel=clear}
function renderBoard(){let calc=calculate();$("#board").innerHTML=state.grid.map((g,i)=>{if(!g)return`<div class="cell empty ${state.selected===i?'selected':''}" data-i="${i}"><span class="muted">${i+1}</span><span class="tap-hint">＋</span></div>`;let p=byId[g.id],c=calc[i];return`<div class="cell ${state.selected===i?'selected':''}" data-i="${i}" draggable="true" style="--cat:${CAT[p.cat].color}">${icon(p)}<span class="badge" style="color:${CAT[p.cat].color}">${p.amp?(g.variant==='blue'?'非傳說1格':'傳說2格'):c.group.length+'連'}</span><span class="lock">${g.locked?'🔒':'○'}</span>${p.amp?'<span class="range-dot"></span>':`<span class="level">${c.level}/${g.rarity}</span>`}</div>`}).join("");document.querySelectorAll(".cell").forEach(el=>{let i=+el.dataset.i;el.onclick=e=>{if(Date.now()<suppressCellClickUntil)return;if(e.target.classList.contains("lock")&&state.grid[i]){state.grid[i].locked=!state.grid[i].locked;state.selected=i;render();return}state.selected=i;if(!state.grid[i]&&isMobile()){renderEditor();openMobilePicker(i);save();return}render()};bindTouchDrag(el,i);el.ondragstart=e=>e.dataTransfer.setData("text/plain","cell:"+i);el.ondragover=e=>{e.preventDefault();el.classList.add("dragover")};el.ondragleave=()=>el.classList.remove("dragover");el.ondrop=e=>{e.preventDefault();let [kind,val]=e.dataTransfer.getData("text/plain").split(":"),result=kind==="cell"?MobileUI.movePart(state.grid,+val,i):MobileUI.placePart(state.grid,i,val,byId);if(!result.ok){flash(result.reason==="duplicate"?"普通零件不可重複":"鎖定格無法移動");return}state.grid=result.grid;state.selected=i;render()}})}
function renderEditor(){let i=state.selected,g=state.grid[i],el=$("#editor");if(i==null){el.innerHTML='<p class="muted">點選格子查看與修改。</p>';return}if(!g){el.innerHTML=`<p>第 ${i+1} 格為空白。從左側拖入零件。</p>`;return}let p=byId[g.id],c=calculate()[i];el.innerHTML=`${icon(p)}<h3>${p.name}</h3><p class="muted">${p.effect}</p>${p.amp?`<label>增幅器品質／範圍<select id="variant"><option value="blue" ${g.variant==='blue'?'selected':''}>非傳說｜1格</option><option value="yellow" ${g.variant==='yellow'?'selected':''}>傳說｜2格</option></select></label><div class="result">影響 <b>${c.targets.length}</b> 顆零件，每顆 +${p.stage} 階</div>`:`<label>自身強化 <input id="level" type="number" min="0" max="${g.rarity}" value="${g.level}"></label><label>最大階數<select id="rarity">${[1,3,5,7].map(n=>`<option ${g.rarity===n?'selected':''}>${n}</option>`).join('')}</select></label><label>0階原值 (%)<input id="base" type="number" step="0.1" value="${g.base??p.base}"></label><label>每提升1階增加 (%)<input id="step" type="number" step="0.1" value="${g.step??p.step}"></label><div class="result">增幅後 <b>${c.level}/${g.rarity}</b><br>連接 ${c.group.length} 顆 ×${c.mult.toFixed(1)}<br>增加 <b>+${c.added.toFixed(1)}%</b><br>最終 <b>${c.final.toFixed(1)}%</b></div>`}<button id="lockBtn">${g.locked?'解除鎖定':'鎖定此格'}</button><button id="deleteBtn" class="danger">移除零件</button>`;for(const id of ["variant","level","rarity","base","step"]){let x=$("#"+id);if(x)x.onchange=()=>{g[id]=id==="variant"?x.value:+x.value;if(id==="rarity")g.level=Math.min(g.level,g.rarity);render()}}$("#lockBtn").onclick=()=>{g.locked=!g.locked;render()};$("#deleteBtn").onclick=()=>{if(!g.locked){state.grid[i]=null;render()}else flash("請先解除鎖定")}}
function renderCalc(){let c=calculate(),s={attack:0,defense:0,support:0,weaken:0};$("#calcBody").innerHTML=c.filter(x=>x&&!x.amp).map(x=>{s[x.p.cat]+=x.final;return`<tr><td>${pos(x.i).map(n=>n+1).join('-')}</td><td>${x.p.name}</td><td style="color:${CAT[x.p.cat].color}">${CAT[x.p.cat].name}</td><td>${x.g.level}/${x.g.rarity}</td><td>${x.level}/${x.g.rarity}</td><td>${x.sources.length?x.sources.map(a=>`第 ${a.i+1} 格 ${a.name} +${a.stage}`).join('<br>'):'—'}</td><td>${x.group.length}</td><td>×${x.mult.toFixed(1)}</td><td>${x.raw.toFixed(1)}%</td><td>+${x.added.toFixed(1)}%</td><td class="final">${x.final.toFixed(1)}%</td></tr>`}).join("");$("#summary").innerHTML=Object.keys(s).map(k=>`<div><span style="color:${CAT[k].color}">${CAT[k].name}總值</span><strong>${s[k].toFixed(1)}%</strong></div>`).join("")}
function score(grid,goal){if(state.strictConnected&&!Connectivity.allCategoriesConnected(grid,byId))return-1e12;if(!EffectEngine.allAmplifiersUseful(grid,byId))return-1e12;let c=calculate(grid),w={attack:.12,defense:.12,support:.12,weaken:.12};if(goal!=="balanced")w[goal]=1;let ability=c.reduce((s,x)=>s+(x&&!x.amp?x.final*w[x.p.cat]:0),0),coverage=c.reduce((s,x)=>s+(x?.amp?x.targets.length*x.p.stage:0),0);return ability+coverage*2}
async function optimize(){let rounds=+$("#rounds").value,goal=$("#build").value,best=structuredClone(state.grid),bestScore=score(best,goal),cur=structuredClone(best),curScore=bestScore,free=cur.map((g,i)=>g?.locked?null:i).filter(x=>x!=null);flash("搜尋最佳配置中…");await new Promise(r=>setTimeout(r,30));for(let n=0;n<rounds;n++){let a=free[Math.floor(Math.random()*free.length)],b=free[Math.floor(Math.random()*free.length)];[cur[a],cur[b]]=[cur[b],cur[a]];let ns=score(cur,goal),temp=1-n/rounds;if(ns>=curScore||Math.random()<Math.exp((ns-curScore)/(20+300*temp)))curScore=ns;else[cur[a],cur[b]]=[cur[b],cur[a]];if(curScore>bestScore){bestScore=curScore;best=structuredClone(cur)}}if(state.strictConnected&&!Connectivity.allCategoriesConnected(best,byId)){flash("找不到完整連接方案：請解除部分鎖定，或改用深入搜尋");render();return}if(!EffectEngine.allAmplifiersUseful(best,byId)){flash("找不到有效增幅方向：請解除增幅器鎖定，或改用深入搜尋");render();return}state.grid=best;flash(`完成：同類完整連接、所有增幅方向有效｜最佳評分 ${bestScore.toFixed(1)}`);render()}
function flash(t){$("#status").textContent=t}
const SHAPE_LABEL={left:"← 左方",right:"→ 右方",up:"↑ 上方",down:"↓ 下方",row:"↔ 水平",col:"↕ 垂直",cross:"✚ 十字",all:"✥ 全方位"};
renderEditor=function(){let i=state.selected,g=state.grid[i],el=$("#editor");if(i==null){el.innerHTML='<p class="muted">點選格子查看與修改。</p>';return}if(!g){el.innerHTML=`<p>第 ${i+1} 格為空白。從左側拖入零件。</p>`;return}let p=byId[g.id],c=calculate()[i];el.innerHTML=`${icon(p)}<h3>${p.name}</h3><p class="muted">${p.effect}</p>${p.amp?`<label>增幅器品質／範圍<select id="variant"><option value="blue" ${g.variant==='blue'?'selected':''}>非傳說｜1格</option><option value="yellow" ${g.variant==='yellow'?'selected':''}>傳說｜2格</option></select></label><div class="result">方向 <b>${SHAPE_LABEL[p.shape]}</b><br>實際影響 <b>${c.targets.length}</b> 顆<br>${c.targets.length?c.targets.map(t=>`第 ${t+1} 格`).join('、'):'<span class="group-state bad">方向無效：沒有覆蓋普通零件</span>'}<br>每顆 +${p.stage} 階</div>`:`<label>自身強化 <input id="level" type="number" min="0" max="${g.rarity}" value="${g.level}"></label><label>最大階數<select id="rarity">${[1,3,5,7].map(n=>`<option ${g.rarity===n?'selected':''}>${n}</option>`).join('')}</select></label><div class="result">截圖最大值 <b>${p.maxValue.toFixed(1)}%</b><br>增幅後 <b>${c.level}/${g.rarity}</b><br>連接 ${c.group.length} 顆 ×${c.mult.toFixed(1)}<br>最終最大值 <b>${c.final.toFixed(1)}%</b></div>`}<button id="lockBtn">${g.locked?'解除鎖定':'鎖定此格'}</button><button id="deleteBtn" class="danger">移除零件</button>`;for(const id of ["variant","level","rarity"]){let x=$("#"+id);if(x)x.onchange=()=>{g[id]=id==="variant"?x.value:+x.value;if(id==="rarity")g.level=Math.min(g.level,g.rarity);render()}}$("#lockBtn").onclick=()=>{g.locked=!g.locked;render()};$("#deleteBtn").onclick=()=>{if(!g.locked){state.grid[i]=null;render()}else flash("請先解除鎖定")}};
renderCalc=function(){let c=calculate(),s={attack:0,defense:0,support:0,weaken:0};$("#calcBody").innerHTML=c.filter(x=>x&&!x.amp).map(x=>{s[x.p.cat]+=x.final;return`<tr><td>${pos(x.i).map(n=>n+1).join('-')}</td><td>${x.p.name}</td><td style="color:${CAT[x.p.cat].color}">${CAT[x.p.cat].name}</td><td>${x.g.level}/${x.g.rarity}</td><td>${x.level}/${x.g.rarity}</td><td>${x.sources.length?x.sources.map(a=>`第 ${a.i+1} 格 ${a.name} +${a.stage}`).join('<br>'):'—'}</td><td>${x.group.length}</td><td>×${x.mult.toFixed(1)}</td><td>${x.p.maxValue.toFixed(1)}%</td><td class="final">${x.final.toFixed(1)}%</td></tr>`}).join("");$("#summary").innerHTML=Object.keys(s).map(k=>`<div><span style="color:${CAT[k].color}">${CAT[k].name}最大總值</span><strong>${s[k].toFixed(1)}%</strong></div>`).join("");let groups=Connectivity.categoryGroups(state.grid,byId),cards=document.querySelectorAll("#summary>div");["attack","defense","support","weaken"].forEach((cat,i)=>{if(!cards[i])return;let count=groups[cat],ok=count<=1;cards[i].insertAdjacentHTML("beforeend",`<span class="group-state ${ok?'ok':'bad'}">${count===0?'未放置':ok?'✓ 完整連接':`⚠ 已分成 ${count} 組`}</span>`)})};
$("#strictConnected").checked=state.strictConnected;
$("#strictConnected").onchange=e=>{state.strictConnected=e.target.checked;save();renderCalc();flash(state.strictConnected?'已啟用：優化時同類必須完整連接':'已關閉完整連接限制')};
$("#optimizeBtn").onclick=optimize;$("#clearBtn").onclick=()=>{state.grid=state.grid.map(x=>x?.locked?x:null);render()};$("#resetBtn").onclick=()=>{localStorage.removeItem("loi-mech-editor-v1");location.reload()};$("#saveBtn").onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="機械工程配置.json";a.click();URL.revokeObjectURL(a.href)};$("#importFile").onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(x.grid?.length!==25)throw 0;state={...state,...x};render();flash("匯入完成")}catch{flash("檔案格式不正確")}};
$("#pickerClose").onclick=closeMobilePicker;$("#pickerBackdrop").onclick=closeMobilePicker;document.addEventListener("keydown",e=>{if(e.key==="Escape")closeMobilePicker()});let pickerStartY=null;$("#pickerHandle").onpointerdown=e=>{pickerStartY=e.clientY;$("#pickerHandle").setPointerCapture(e.pointerId)};$("#pickerHandle").onpointerup=e=>{if(pickerStartY!=null&&e.clientY-pickerStartY>60)closeMobilePicker();pickerStartY=null};
(function selfTest(){console.assert(bonus(1)===1&&bonus(7)===2.2,"連接倍率錯誤");console.assert(initial.length===25,"盤面不是25格")})();render();
